name: ✨ OSS Feature Request
description: Suggest a feature or enhancement for the open-source SAML Shield library
title: "[Feature] <brief summary>"
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ This form is for OSS users only. If you're using the **SaaS-managed version**, please request features in the [Stytch Slack](https://join.slack.com/t/stytch/shared_invite/zt-2n6jvvgzm-fAyxi_kr1uqGc15UJqxiPw).

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: It’s difficult to...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What would you like to see added?
      placeholder: I’d like the library to support...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      placeholder: Related links, existing tools, alternatives considered, etc.
    validations:
      required: false
